version: 1
jobs:
  build:
    docker:
      - image: alpine
    steps:
        - checkout
        - run: apk update && apk add openssh-client bash sshpass
        - run: sshpass -e scp -o stricthostkeychecking=no -r . csl@lab1.cybersecurity.li:/home/csl
workflows:
  version: 1
  build:
    jobs:
      - build
